from datetime import datetime


def build_investment_report(
    ticker,
    recommendation_json,
    backtest_json,
    backtest_period="1Y"
):
    confidence = "High" if recommendation_json["momentum_strength"] >= 70 else ("Medium" if recommendation_json["momentum_strength"] >= 40 else "Low")
    trade_win_rate = backtest_json.get("win_rate_trade", backtest_json.get("win_rate_daily", 0.0))
    closed_trades = int(backtest_json.get("closed_trades", 0))
    risk_warning = (
        "Momentum strategies are sensitive to trend reversals and market regime changes. "
        "Position sizing and stop-loss rules are recommended."
    )
    report = (
        "## Investment Recommendation Report\n\n"
        f"**Ticker**: {ticker}  \n"
        f"**Date**: {datetime.now().strftime('%Y-%m-%d')}  \n"
        f"**Recommendation**: **{recommendation_json['recommendation']}** (Signal Strength: {recommendation_json['momentum_strength']}/100)  \n"
        f"**Confidence Level**: {confidence}\n\n"
        "### Rationale\n"
        f"{recommendation_json['reasoning']}\n\n"
        f"### Backtest Performance ({backtest_period})\n"
        "| Metric | Value |\n"
        "|--------|-------|\n"
        f"| Annualized Return | {backtest_json['annualized_return']:.2%} |\n"
        f"| Annualized Volatility | {backtest_json['annualized_volatility']:.2%} |\n"
        f"| Sharpe Ratio | {backtest_json['sharpe_ratio']:.2f} |\n"
        f"| Maximum Drawdown | {backtest_json['max_drawdown_pct'] / 100:.2%} |\n"
        f"| Win Rate (Per Trade) | {trade_win_rate:.2%} |\n"
        f"| Closed Trades | {closed_trades} |\n\n"
        "### Risk Considerations\n"
        f"{risk_warning}\n\n"
        "### Disclaimer\n"
        "This report is generated by a large language model and is for informational purposes only. "
        "It does not constitute financial advice or a recommendation to buy or sell any security. "
        "Past performance does not guarantee future results. Always conduct your own research before making investment decisions.\n"
    )
    return report
